### ISSUE TITLE
[Bindable]private vars cause GCC warning

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#113] opened 2020-01-27 10:46 UTC
`[Bindable]private var foo:String` produces the following comment:

````
/** @export
  * @private
  * @type {string} */
````
The `@private` tag causes the following warning: `WARNING - Parse error. extra visibility tag`

I don't think the `@export` tag is necessary considering this is inside an `Object.defineProperties()` (something else which should be considered). Either way, I think `@export` and `@private` are mutually exclusive.

**Comment by Harbs** [comment] 2020-01-27 10:47
FWIW, I think the same goes for `protected`.

**Comment by joshtynjala** [comment] 2021-04-26 20:55
Closing because I can't reproduce anymore. The change to exporting dynamically in release builds probably fixed it.

**Closed by joshtynjala** 2021-04-26 20:55 UTC
Labels: bug
