### ISSUE TITLE
Externs warning

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#109] opened 2020-01-02 21:59 UTC
When compiling HelloWorld, we get the following warning:
````
    [mxmlc] Jan 02, 2020 10:54:05 PM com.google.javascript.jscomp.LoggerErrorManager println
    [mxmlc] WARNING: externs/dialogPolyfill.js:19: WARNING - accessing name dialogPolyfill in externs has no effect. Perhaps you forgot to add a var keyword?
    [mxmlc] dialogPolyfill = function() {
    [mxmlc] ^^^^^^^^^^^^^^
    [mxmlc] 
    [mxmlc] Jan 02, 2020 10:54:05 PM com.google.javascript.jscomp.LoggerErrorManager println
    [mxmlc] WARNING: externs/dialogPolyfill.js:19: WARNING - variable dialogPolyfill is undeclared
    [mxmlc] dialogPolyfill = function() {
    [mxmlc] ^^^^^^^^^^^^^^
    [mxmlc] 
    [mxmlc] Jan 02, 2020 10:54:05 PM com.google.javascript.jscomp.LoggerErrorManager println
    [mxmlc] WARNING: externs/dialogPolyfill.js:27: WARNING - name dialogPolyfill is not defined in the externs.
    [mxmlc] dialogPolyfill.registerDialog = function(dialog) {
````
This appears to be from the following in Jewel:
````
/**
 * Generated by Apache Royale Compiler from dialogPolyfill.as
 * dialogPolyfill
 *
 * @fileoverview
 * @externs
 *
 * @suppress {checkTypes|accessControls}
 */


/** 
 * <inject_html>
 * <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.js"></script>
 * <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.css">
 * </inject_html>
 * @constructor
 */
dialogPolyfill = function() {
};


/**
 * @export
 * @param {Element} dialog
 */
dialogPolyfill.registerDialog = function(dialog) {
};
````
which is generated by this:
````
package
{
	/**
	 * @externs
	 */
	COMPILE::JS
	public class dialogPolyfill
	{
		/** 
         * <inject_html>
         * <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.js"></script>
         * <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.css">
         * </inject_html>
		 */
		public function dialogPolyfill(){}
		 
		public static function registerDialog(dialog:Element):void {}
	}
}
````
I'm not sure why that's the result or how to fix it.

**Comment by joshtynjala** [comment] 2021-04-26 21:27
Closing because this issue will no longer reproduce. I find that the warnings about dialogPolyfill are not present anymore when compiling a release build of HelloWorld.

**Closed by joshtynjala** 2021-04-26 21:27 UTC
Labels: bug
