### ISSUE TITLE
sortOn is not working in type of ArrayCollection which works in Flash

### ISSUE THREAD

**Issue by ekumar2** [apache/royale-compiler#205] opened 2021-12-14 12:56 UTC
`var arr:ArrayCollection = new ArrayCollection();
arr.addItem({label:"Z", data:"first"});
arr.addItem({label:"C", data:"second"});
arr.addItem({label:"E", data:"third"});

arr.sortOn('label');

expected output -
{label:"C", data:"second"};
{label:"E", data:"third"};
{label:"Z", data:"first"};
`

The sortOn works on ArrayCollection and it sorts the object of Arrays based on property passed.

**Comment by yishayw** [comment] 2021-12-14 14:46
> `var arr:Array = new ArrayCollection(); arr.push({label:"Z", data:"first"}); arr.push({label:"C", data:"second"}); arr.push({label:"E", data:"third"});
> 


Is arr and Array or an ArrayCollection ? Looks like you are declaring it as an Array and assigning to it an ArrayCollection.

**Comment by greg-dove** [comment] 2022-01-04 04:21
@ekumar2 Can we consider this closed? As Yishay said, this does appear to be invalid:
`var arr:Array = new ArrayCollection()`

if it was instead:
```
var arr:Array = [];
arr.push({label:"Z", data:"first"});
arr.push({label:"C", data:"second"});
arr.push({label:"E", data:"third"});
arr.sortOn('label');
```
...and the results were not correct in this case, then please confirm that is the issue, thanks.

**Comment by ekumar2** [comment] 2022-01-04 05:01
It is ArrayCollection on... @greg-dove

**Comment by joshtynjala** [comment] 2022-01-06 18:07
I have just confirmed that the `ArrayCollection` class in Flex did not have a `sortOn()` method. I think that you are mistakenly remembering the `sortOn()` method of the `Array` class.

**Closed by joshtynjala** 2022-01-06 18:07 UTC
