### ISSUE TITLE
Internal Error NPE thrown for try-catch declaration in mxml

### ISSUE THREAD

**Issue by Laturine** [apache/royale-compiler#191] opened 2021-07-14 21:03 UTC
Hi Here's the sample test case
*** Foo.mxml ***
```as3
public function bar():void {
	    try{
                trace("hi");
            }
            catch(e:Error){
                var t :TitleWindow = new TitleWindow();
            }
}
```
This will blow up. Here's the stack trace.
`
col: 4 Internal error: java.lang.NullPointerException
        at org.apache.royale.compiler.internal.as.codegen.ABCGeneratingReducer.reduce_declName(ABCGeneratingReducer.java:5560)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.action_437(CmcEmitter.java:6237)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:9067)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39127)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39146)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:9410)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39127)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39155)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39146)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39155)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39155)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39146)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
        at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.burm(CmcEmitter.java:39406)
        at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateInstructions(ABCGenerator.java:235)
        at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:416)  
        at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:370)  
        at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateFunction(ABCGenerator.java:272)
        at org.apache.royale.compiler.internal.as.codegen.ClassDirectiveProcessor.declareFunction(ClassDirectiveProcessor.java:880)
        at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:218)        
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:1119)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:864)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:834)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMXMLScript(MXMLClassDirectiveProcessor.java:4232)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:985)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:864)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:834)
        at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMainClassDefinitionNode(MXMLClassDirectiveProcessor.java:656)
        at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareMXMLDocument(GlobalDirectiveProcessor.java:551)
        at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:236)        
        at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:192)
        at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:126)
        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleABCBytesRequest(MXMLCompilationUnit.java:202) 
        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:876)        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:109)
        at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:313)
        at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:309)
        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

                        override public function get data():Object {
                        ^

10.254273 seconds
The terminal process "C:\jdk1.8.0_144\bin\java.exe '-jar', 'c:\Users\developer\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\bin\asconfigc.jar', '--sdk', 'c:\apache_royale_nightlies\3064\apache-royale-0.9.8-bin-js\royale-asjs', '--debug=true', '--project', 'c:\Users\developer\Desktop\repos\royale_vscode\royale\trunk\asconfig.json'" terminated with exit code: 3

Here's my compiler options:
`
MXMLJSC
+royalelib=c:\apache_royale_nightlies\3064\apache-royale-0.9.8-bin-js\royale-asjs\frameworks
--debug=true
--source-path+=src/main/royale
--targets=JSRoyale
--load-config+=tbt-defines.xml
--default-frame-rate=60
--default-background-color=#FFFFFF
--default-size
800
600
--keep-as3-metadata+=Bindable
--show-unused-type-selector-warnings=true
--verbose-stacktraces=false
--accessible=false
--strict=true
--benchmark=false
--static-link-runtime-shared-libraries=false
--use-network=true
--use-resource-bundle-metadata=true
--warnings=true
--optimize=false
+configname=flex
--`

**Comment by joshtynjala** [comment] 2021-09-08 16:28
I can reproduce this issue. It seems to happen when a variable is declared in the `catch` block. As best I can tell, it reproduces with any type (for instance, I changed it to `String` in the example below instead of `TitleWindow` from the original report, and it still reproduced).

```actionscript
public function bar():void {
    try {
        trace("hi");
    }
    catch(e:Error) {
        var s:String;
    }
}
```

This is the method in `ABCGeneratingReducer` with the null exception:

```java
public Name reduce_declName(IASNode iNode )
{
    // We are the name of a declaration, get the containing DefinitionNode and grab the
    // name from there
    BaseDefinitionNode bdn = (BaseDefinitionNode)iNode.getAncestorOfType(BaseDefinitionNode.class);
    DefinitionBase db = bdn.getDefinition();
    Name n = db.getMName(currentScope.getProject());
    return n;
}
```

The result of `bdn.getDefinition()` returns `null`. The `BaseDefinitionNode` refers to the local variable in the `catch` block. As best I can tell, its definition must not have been populated. Not sure why yet. Needs further investigation.

**Comment by greg-dove** [comment] 2021-12-08 19:34
I will investigate this when I have some spare time coming up. I think I might have an understanding of what is going on after I recently did something to support multiple catches in JS.

**Comment by greg-dove** [comment] 2022-01-04 02:59
@joshtynjala @Laturine I believe this is fixed now. Please let me know if you see any problems. I think it will be slightly more strict than the original falcon compiler in some cases now to report naming conflicts as well.
I added an extra test here:  https://github.com/apache/royale-asjs/blob/3e133c3450a99b58835810df63c9bb7ae7b9c8cd/frameworks/projects/Core/src/test/royale/flexUnitTests/language/LanguageTesterTestTryCatch.as#L129

@joshtynjala fyi the issue was somewhat like I expected, but as is often the case, was a little trickier than I'd hoped. CatchScope is a strange creature. The local scope is only intended for storing the catch parameter definition and all other name declarations are supposed to be hoisted to the enclosing scope. That part was working, but in this case the name lookups were attempting to find the definition by name in the non-hoisting scope, which only contains the catch parameter definition. That is why it was coming back as null when doing the definition lookup by name. As to why it was only doing that from mxml and not regular actionscript, that was less evident, although there seems to be more repetitive passes over the same code block from mxml, as parsing the mxml file has more 'stages'.
I did test the changes with a String declaration inside a catch block which you can see in the unit test above. And I did test very similar code separately, inside an mxml script block (after repro'ing the original issue in that case).

**Comment by greg-dove** [comment] 2022-01-04 04:15
FYI If no-one else verifies the fix and closes this issue within a few days, I will close it myself.

**Comment by joshtynjala** [comment] 2022-01-06 18:04
I played around with it a bit, and everything looks good to me! Thanks, @greg-dove!

**Closed by joshtynjala** 2022-01-06 18:04 UTC
Labels: bug
