### ISSUE TITLE
Vector.removeAt() returns Array in JS

### ISSUE THREAD

**Issue by yishayw** [apache/royale-compiler#91] opened 2019-07-29 09:35 UTC
var item:SpreadTextData = spreadTextDataItems.removeAt(notificationBody.fromIndex) as SpreadTextData;

Transpiles to

    var /** @type {com.printui.model.SpreadTextData} */ item = spreadTextDataItems.splice(notificationBody.fromIndex, 1);

which is an Array

**Comment by greg-dove** [comment] 2019-07-29 21:44
Duplicate of #92

**Comment by Harbs** [comment] 2019-07-30 10:07
To be clear, the correct JS is:
`var /** @type {A} */ item = vectorAsArray.splice(index, 1)[0];`

instead of:
`var /** @type {A} */ item = vectorAsArray.splice(index, 1);`

**Comment by Harbs** [comment] 2019-07-30 10:10
Fixed in 34ff8d4

**Closed by Harbs** 2019-07-30 10:10 UTC
